no message

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -2,7 +2,7 @@
 # bin/detect <build-dir>
 
 if [ -f "$1/conf/nginx.conf.erb" ] then
-echo "nginx" && exit 0
+	echo "nginx" && exit 0
 else
-  echo "Could not find conf/nginx.conf.erb, build cannot continue." && exit 1
+	echo "Could not find conf/nginx.conf.erb, build cannot continue." && exit 1
 fi
